DROP DATABASE IF EXISTS tacotime_db;
CREATE DATABASE tacotime_db;
USE tacotime_db;

CREATE TABLE tacos
(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	devoured BOOLEAN,
	PRIMARY KEY (id)
);
